---

- name: download prometheus memcached exporter binary
  get_url:
    url: "{{ url }}"
    dest: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_memcached_exporter_release_name }}.tar.gz"

- name: unarchive binary tarball
  unarchive:
    copy: false
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_memcached_exporter_release_name }}.tar.gz"
    dest: "{{ prometheus_exporters_common_dist_dir }}"
    creates: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_memcached_exporter_release_name }}/memcached_exporter"
  register: prometheus_memcached_exporter_updated
  notify:
    - restart memcached exporter

- name: update group and owner for files
  file:
    path: "{{ prometheus_memcached_exporter_release_name }}"
    state: directory
    recurse: true
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"
  when: prometheus_memcached_exporter_updated | changed

- name: create symlink to the current release
  file:
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_memcached_exporter_release_name }}"
    path: "{{ prometheus_exporters_common_root_dir }}/memcached_exporter_current"
    state: link

- name: create systemd service unit
  template:
    src: etc/systemd/system/prometheus-memcached-exporter.service.j2
    dest: /etc/systemd/system/prometheus-memcached-exporter.service
    owner: root
    group: root
    mode: 0644
  when: service_mgr | default(ansible_service_mgr) == 'systemd'
  notify:
    - reenable memcached exporter service
    - restart memcached exporter

- name: Looking which version of upstart is install
  command: initctl version
  when: service_mgr | default(ansible_service_mgr) == 'upstart'
  register: upstart_version

- name: create init service unit
  template:
    src: etc/init/prometheus-memcached-exporter.conf.j2
    dest: /etc/init/prometheus-memcached-exporter.conf
    owner: root
    group: root
    mode: 0644
  when: service_mgr | default(ansible_service_mgr) == 'upstart'
  notify:
    - reinit memcached exporter
    - restart memcached exporter

- name: create sysvinit service unit
  template:
    src: etc/init.d/prometheus-memcached-exporter.j2
    dest: /etc/init.d/prometheus-memcached-exporter
    owner: root
    group: root
    mode: 0755
  when: service_mgr | default(ansible_service_mgr) in [ 'sysvinit', 'service' ]
  notify:
    - restart memcached exporter

- meta: flush_handlers

- name: ensure prometheus memcached exporter service is enabled and started
  service:
    name: prometheus-memcached-exporter
    state: started
    enabled: true
